--
-- Drop tables
--

DROP TABLE IF EXISTS allergie CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS acte_medicaux CASCADE;
DROP TABLE IF EXISTS fichier_num CASCADE;
DROP TABLE IF EXISTS medecin CASCADE;
DROP TABLE IF EXISTS service CASCADE;
DROP TABLE IF EXISTS fonction CASCADE;
DROP TABLE IF EXISTS touche CASCADE;
DROP TABLE IF EXISTS contient CASCADE;
DROP TABLE IF EXISTS occupe CASCADE;
DROP VIEW IF EXISTS medecin_dispo CASCADE;

